"use client";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ThemeProvider } from "next-themes";
import { Nav } from "@/component/Nav";

const inter = Inter({ subsets: ["latin"] });

// remember to bring back the export before the const medatdata after
//and then fix the issue with the use client
const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {" "}
        <ThemeProvider attribute="class">
          {" "}
          <Nav />
          {children}{" "}
        </ThemeProvider>
      </body>
    </html>
  );
}
